// Nhãn từng châu lục hiển thị trên giao diện
const CONTINENTS = [
  { key: "asia", label: "Châu Á", icon: "🌏" },
  { key: "europe", label: "Châu Âu", icon: "🏰" },
  { key: "africa", label: "Châu Phi", icon: "🦁" },
  { key: "america", label: "Châu Mỹ", icon: "🗽" },
  { key: "oceania", label: "Châu Đại Dương", icon: "🏝️" },
];

// [tên thành phố, quốc gia, múi giờ IANA, châu lục, loại ("capital" | "financial"), nổi bật?]
// Mỗi châu lục có đúng 5 thành phố "nổi bật" (featured) hiển thị mặc định.
// Toàn bộ thành phố còn lại truy xuất qua thanh tìm kiếm và có thể "Thêm" để ghim cố định.
const CITY_DATA = [
  // ===== CHÂU Á =====
  ["Hà Nội", "Việt Nam", "Asia/Ho_Chi_Minh", "asia", "capital", true],
  ["TP. Hồ Chí Minh", "Việt Nam", "Asia/Ho_Chi_Minh", "asia", "financial", false],
  ["Tokyo", "Nhật Bản", "Asia/Tokyo", "asia", "capital", true],
  ["Seoul", "Hàn Quốc", "Asia/Seoul", "asia", "capital", false],
  ["Bắc Kinh", "Trung Quốc", "Asia/Shanghai", "asia", "capital", false],
  ["Thượng Hải", "Trung Quốc", "Asia/Shanghai", "asia", "financial", false],
  ["Hồng Kông", "Trung Quốc (Hồng Kông)", "Asia/Hong_Kong", "asia", "financial", true],
  ["Đài Bắc", "Đài Loan", "Asia/Taipei", "asia", "capital", false],
  ["Singapore", "Singapore", "Asia/Singapore", "asia", "capital", true],
  ["Kuala Lumpur", "Malaysia", "Asia/Kuala_Lumpur", "asia", "capital", false],
  ["Bangkok", "Thái Lan", "Asia/Bangkok", "asia", "capital", false],
  ["Jakarta", "Indonesia", "Asia/Jakarta", "asia", "capital", false],
  ["Manila", "Philippines", "Asia/Manila", "asia", "capital", false],
  ["Phnom Penh", "Campuchia", "Asia/Phnom_Penh", "asia", "capital", false],
  ["Vientiane", "Lào", "Asia/Vientiane", "asia", "capital", false],
  ["Naypyidaw", "Myanmar", "Asia/Yangon", "asia", "capital", false],
  ["Yangon", "Myanmar", "Asia/Yangon", "asia", "financial", false],
  ["Dhaka", "Bangladesh", "Asia/Dhaka", "asia", "capital", false],
  ["New Delhi", "Ấn Độ", "Asia/Kolkata", "asia", "capital", false],
  ["Mumbai", "Ấn Độ", "Asia/Kolkata", "asia", "financial", false],
  ["Islamabad", "Pakistan", "Asia/Karachi", "asia", "capital", false],
  ["Karachi", "Pakistan", "Asia/Karachi", "asia", "financial", false],
  ["Kathmandu", "Nepal", "Asia/Kathmandu", "asia", "capital", false],
  ["Thimphu", "Bhutan", "Asia/Thimphu", "asia", "capital", false],
  ["Colombo", "Sri Lanka", "Asia/Colombo", "asia", "capital", false],
  ["Malé", "Maldives", "Indian/Maldives", "asia", "capital", false],
  ["Kabul", "Afghanistan", "Asia/Kabul", "asia", "capital", false],
  ["Tashkent", "Uzbekistan", "Asia/Tashkent", "asia", "capital", false],
  ["Astana", "Kazakhstan", "Asia/Almaty", "asia", "capital", false],
  ["Almaty", "Kazakhstan", "Asia/Almaty", "asia", "financial", false],
  ["Bishkek", "Kyrgyzstan", "Asia/Bishkek", "asia", "capital", false],
  ["Dushanbe", "Tajikistan", "Asia/Dushanbe", "asia", "capital", false],
  ["Ashgabat", "Turkmenistan", "Asia/Ashgabat", "asia", "capital", false],
  ["Ulaanbaatar", "Mông Cổ", "Asia/Ulaanbaatar", "asia", "capital", false],
  ["Bình Nhưỡng", "Triều Tiên", "Asia/Pyongyang", "asia", "capital", false],
  ["Dubai", "UAE", "Asia/Dubai", "asia", "financial", true],
  ["Abu Dhabi", "UAE", "Asia/Dubai", "asia", "capital", false],
  ["Riyadh", "Ả Rập Xê Út", "Asia/Riyadh", "asia", "capital", false],
  ["Doha", "Qatar", "Asia/Qatar", "asia", "capital", false],
  ["Kuwait City", "Kuwait", "Asia/Kuwait", "asia", "capital", false],
  ["Manama", "Bahrain", "Asia/Bahrain", "asia", "capital", false],
  ["Muscat", "Oman", "Asia/Muscat", "asia", "capital", false],
  ["Amman", "Jordan", "Asia/Amman", "asia", "capital", false],
  ["Beirut", "Lebanon", "Asia/Beirut", "asia", "capital", false],
  ["Damascus", "Syria", "Asia/Damascus", "asia", "capital", false],
  ["Baghdad", "Iraq", "Asia/Baghdad", "asia", "capital", false],
  ["Tehran", "Iran", "Asia/Tehran", "asia", "capital", false],
  ["Tel Aviv", "Israel", "Asia/Jerusalem", "asia", "financial", false],
  ["Ankara", "Thổ Nhĩ Kỳ", "Europe/Istanbul", "asia", "capital", false],
  ["Istanbul", "Thổ Nhĩ Kỳ", "Europe/Istanbul", "asia", "financial", false],
  ["Baku", "Azerbaijan", "Asia/Baku", "asia", "capital", false],
  ["Yerevan", "Armenia", "Asia/Yerevan", "asia", "capital", false],
  ["Tbilisi", "Georgia", "Asia/Tbilisi", "asia", "capital", false],
  ["Sana'a", "Yemen", "Asia/Aden", "asia", "capital", false],
  ["Dili", "Timor-Leste", "Asia/Dili", "asia", "capital", false],
  ["Bandar Seri Begawan", "Brunei", "Asia/Brunei", "asia", "capital", false],

  // ===== CHÂU ÂU =====
  ["London", "Anh", "Europe/London", "europe", "capital", true],
  ["Paris", "Pháp", "Europe/Paris", "europe", "capital", true],
  ["Berlin", "Đức", "Europe/Berlin", "europe", "capital", true],
  ["Frankfurt", "Đức", "Europe/Berlin", "europe", "financial", false],
  ["Moscow", "Nga", "Europe/Moscow", "europe", "capital", true],
  ["Zurich", "Thuỵ Sĩ", "Europe/Zurich", "europe", "financial", true],
  ["Bern", "Thuỵ Sĩ", "Europe/Zurich", "europe", "capital", false],
  ["Rome", "Ý", "Europe/Rome", "europe", "capital", false],
  ["Madrid", "Tây Ban Nha", "Europe/Madrid", "europe", "capital", false],
  ["Lisbon", "Bồ Đào Nha", "Europe/Lisbon", "europe", "capital", false],
  ["Amsterdam", "Hà Lan", "Europe/Amsterdam", "europe", "capital", false],
  ["Brussels", "Bỉ", "Europe/Brussels", "europe", "capital", false],
  ["Luxembourg", "Luxembourg", "Europe/Luxembourg", "europe", "financial", false],
  ["Dublin", "Ireland", "Europe/Dublin", "europe", "capital", false],
  ["Vienna", "Áo", "Europe/Vienna", "europe", "capital", false],
  ["Stockholm", "Thuỵ Điển", "Europe/Stockholm", "europe", "capital", false],
  ["Oslo", "Na Uy", "Europe/Oslo", "europe", "capital", false],
  ["Copenhagen", "Đan Mạch", "Europe/Copenhagen", "europe", "capital", false],
  ["Helsinki", "Phần Lan", "Europe/Helsinki", "europe", "capital", false],
  ["Reykjavik", "Iceland", "Atlantic/Reykjavik", "europe", "capital", false],
  ["Warsaw", "Ba Lan", "Europe/Warsaw", "europe", "capital", false],
  ["Prague", "Séc", "Europe/Prague", "europe", "capital", false],
  ["Budapest", "Hungary", "Europe/Budapest", "europe", "capital", false],
  ["Bratislava", "Slovakia", "Europe/Bratislava", "europe", "capital", false],
  ["Ljubljana", "Slovenia", "Europe/Ljubljana", "europe", "capital", false],
  ["Zagreb", "Croatia", "Europe/Zagreb", "europe", "capital", false],
  ["Belgrade", "Serbia", "Europe/Belgrade", "europe", "capital", false],
  ["Sarajevo", "Bosnia và Herzegovina", "Europe/Sarajevo", "europe", "capital", false],
  ["Podgorica", "Montenegro", "Europe/Podgorica", "europe", "capital", false],
  ["Skopje", "Bắc Macedonia", "Europe/Skopje", "europe", "capital", false],
  ["Tirana", "Albania", "Europe/Tirane", "europe", "capital", false],
  ["Athens", "Hy Lạp", "Europe/Athens", "europe", "capital", false],
  ["Sofia", "Bulgaria", "Europe/Sofia", "europe", "capital", false],
  ["Bucharest", "Romania", "Europe/Bucharest", "europe", "capital", false],
  ["Chisinau", "Moldova", "Europe/Chisinau", "europe", "capital", false],
  ["Kyiv", "Ukraine", "Europe/Kyiv", "europe", "capital", false],
  ["Minsk", "Belarus", "Europe/Minsk", "europe", "capital", false],
  ["Vilnius", "Litva", "Europe/Vilnius", "europe", "capital", false],
  ["Riga", "Latvia", "Europe/Riga", "europe", "capital", false],
  ["Tallinn", "Estonia", "Europe/Tallinn", "europe", "capital", false],
  ["Valletta", "Malta", "Europe/Malta", "europe", "capital", false],
  ["Nicosia", "Síp", "Asia/Nicosia", "europe", "capital", false],
  ["Monaco", "Monaco", "Europe/Monaco", "europe", "financial", false],
  ["Vatican", "Vatican", "Europe/Vatican", "europe", "capital", false],
  ["San Marino", "San Marino", "Europe/San_Marino", "europe", "capital", false],
  ["Andorra la Vella", "Andorra", "Europe/Andorra", "europe", "capital", false],

  // ===== CHÂU PHI =====
  ["Cairo", "Ai Cập", "Africa/Cairo", "africa", "capital", true],
  ["Lagos", "Nigeria", "Africa/Lagos", "africa", "financial", true],
  ["Abuja", "Nigeria", "Africa/Lagos", "africa", "capital", false],
  ["Johannesburg", "Nam Phi", "Africa/Johannesburg", "africa", "financial", true],
  ["Pretoria", "Nam Phi", "Africa/Johannesburg", "africa", "capital", false],
  ["Cape Town", "Nam Phi", "Africa/Johannesburg", "africa", "capital", false],
  ["Nairobi", "Kenya", "Africa/Nairobi", "africa", "capital", true],
  ["Casablanca", "Morocco", "Africa/Casablanca", "africa", "financial", true],
  ["Rabat", "Morocco", "Africa/Casablanca", "africa", "capital", false],
  ["Algiers", "Algeria", "Africa/Algiers", "africa", "capital", false],
  ["Tunis", "Tunisia", "Africa/Tunis", "africa", "capital", false],
  ["Tripoli", "Libya", "Africa/Tripoli", "africa", "capital", false],
  ["Khartoum", "Sudan", "Africa/Khartoum", "africa", "capital", false],
  ["Addis Ababa", "Ethiopia", "Africa/Addis_Ababa", "africa", "capital", false],
  ["Accra", "Ghana", "Africa/Accra", "africa", "capital", false],
  ["Dakar", "Senegal", "Africa/Dakar", "africa", "capital", false],
  ["Abidjan", "Bờ Biển Ngà", "Africa/Abidjan", "africa", "capital", false],
  ["Yaoundé", "Cameroon", "Africa/Douala", "africa", "capital", false],
  ["Kinshasa", "CHDC Congo", "Africa/Kinshasa", "africa", "capital", false],
  ["Luanda", "Angola", "Africa/Luanda", "africa", "capital", false],
  ["Lusaka", "Zambia", "Africa/Lusaka", "africa", "capital", false],
  ["Harare", "Zimbabwe", "Africa/Harare", "africa", "capital", false],
  ["Maputo", "Mozambique", "Africa/Maputo", "africa", "capital", false],
  ["Windhoek", "Namibia", "Africa/Windhoek", "africa", "capital", false],
  ["Gaborone", "Botswana", "Africa/Gaborone", "africa", "capital", false],
  ["Dodoma", "Tanzania", "Africa/Dar_es_Salaam", "africa", "capital", false],
  ["Dar es Salaam", "Tanzania", "Africa/Dar_es_Salaam", "africa", "financial", false],
  ["Kampala", "Uganda", "Africa/Kampala", "africa", "capital", false],
  ["Kigali", "Rwanda", "Africa/Kigali", "africa", "capital", false],
  ["Mogadishu", "Somalia", "Africa/Mogadishu", "africa", "capital", false],
  ["Djibouti", "Djibouti", "Africa/Djibouti", "africa", "capital", false],
  ["Bamako", "Mali", "Africa/Bamako", "africa", "capital", false],
  ["Ouagadougou", "Burkina Faso", "Africa/Ouagadougou", "africa", "capital", false],
  ["Niamey", "Niger", "Africa/Niamey", "africa", "capital", false],
  ["N'Djamena", "Chad", "Africa/Ndjamena", "africa", "capital", false],
  ["Bangui", "CH Trung Phi", "Africa/Bangui", "africa", "capital", false],
  ["Libreville", "Gabon", "Africa/Libreville", "africa", "capital", false],
  ["Brazzaville", "Congo", "Africa/Brazzaville", "africa", "capital", false],
  ["Malabo", "Guinea Xích Đạo", "Africa/Malabo", "africa", "capital", false],
  ["Nouakchott", "Mauritania", "Africa/Nouakchott", "africa", "capital", false],
  ["Freetown", "Sierra Leone", "Africa/Freetown", "africa", "capital", false],
  ["Monrovia", "Liberia", "Africa/Monrovia", "africa", "capital", false],
  ["Conakry", "Guinea", "Africa/Conakry", "africa", "capital", false],
  ["Bissau", "Guinea-Bissau", "Africa/Bissau", "africa", "capital", false],
  ["Banjul", "Gambia", "Africa/Banjul", "africa", "capital", false],
  ["Lomé", "Togo", "Africa/Lome", "africa", "capital", false],
  ["Porto-Novo", "Benin", "Africa/Porto-Novo", "africa", "capital", false],
  ["Praia", "Cabo Verde", "Atlantic/Cape_Verde", "africa", "capital", false],
  ["Antananarivo", "Madagascar", "Indian/Antananarivo", "africa", "capital", false],
  ["Port Louis", "Mauritius", "Indian/Mauritius", "africa", "capital", false],
  ["Victoria", "Seychelles", "Indian/Mahe", "africa", "capital", false],
  ["Asmara", "Eritrea", "Africa/Asmara", "africa", "capital", false],
  ["Juba", "Nam Sudan", "Africa/Juba", "africa", "capital", false],
  ["Lilongwe", "Malawi", "Africa/Blantyre", "africa", "capital", false],
  ["Bujumbura", "Burundi", "Africa/Bujumbura", "africa", "capital", false],
  ["Moroni", "Comoros", "Indian/Comoro", "africa", "capital", false],
  ["São Tomé", "São Tomé và Príncipe", "Africa/Sao_Tome", "africa", "capital", false],
  ["Mbabane", "Eswatini", "Africa/Mbabane", "africa", "capital", false],
  ["Maseru", "Lesotho", "Africa/Maseru", "africa", "capital", false],

  // ===== CHÂU MỸ =====
  ["Washington D.C.", "Mỹ", "America/New_York", "america", "capital", true],
  ["New York", "Mỹ", "America/New_York", "america", "financial", true],
  ["Chicago", "Mỹ", "America/Chicago", "america", "financial", false],
  ["Los Angeles", "Mỹ", "America/Los_Angeles", "america", "financial", false],
  ["Ottawa", "Canada", "America/Toronto", "america", "capital", false],
  ["Toronto", "Canada", "America/Toronto", "america", "financial", true],
  ["Vancouver", "Canada", "America/Vancouver", "america", "financial", false],
  ["Mexico City", "Mexico", "America/Mexico_City", "america", "capital", true],
  ["Guatemala City", "Guatemala", "America/Guatemala", "america", "capital", false],
  ["Belmopan", "Belize", "America/Belize", "america", "capital", false],
  ["San Salvador", "El Salvador", "America/El_Salvador", "america", "capital", false],
  ["Tegucigalpa", "Honduras", "America/Tegucigalpa", "america", "capital", false],
  ["Managua", "Nicaragua", "America/Managua", "america", "capital", false],
  ["San José", "Costa Rica", "America/Costa_Rica", "america", "capital", false],
  ["Panama City", "Panama", "America/Panama", "america", "capital", false],
  ["Havana", "Cuba", "America/Havana", "america", "capital", false],
  ["Kingston", "Jamaica", "America/Jamaica", "america", "capital", false],
  ["Port-au-Prince", "Haiti", "America/Port-au-Prince", "america", "capital", false],
  ["Santo Domingo", "Cộng hòa Dominica", "America/Santo_Domingo", "america", "capital", false],
  ["Nassau", "Bahamas", "America/Nassau", "america", "capital", false],
  ["Bridgetown", "Barbados", "America/Barbados", "america", "capital", false],
  ["Port of Spain", "Trinidad và Tobago", "America/Port_of_Spain", "america", "capital", false],
  ["Bogotá", "Colombia", "America/Bogota", "america", "capital", false],
  ["Caracas", "Venezuela", "America/Caracas", "america", "capital", false],
  ["Quito", "Ecuador", "America/Guayaquil", "america", "capital", false],
  ["Lima", "Peru", "America/Lima", "america", "capital", false],
  ["La Paz", "Bolivia", "America/La_Paz", "america", "capital", false],
  ["Santiago", "Chile", "America/Santiago", "america", "capital", false],
  ["Buenos Aires", "Argentina", "America/Argentina/Buenos_Aires", "america", "capital", false],
  ["Montevideo", "Uruguay", "America/Montevideo", "america", "capital", false],
  ["Asunción", "Paraguay", "America/Asuncion", "america", "capital", false],
  ["Brasília", "Brazil", "America/Sao_Paulo", "america", "capital", false],
  ["São Paulo", "Brazil", "America/Sao_Paulo", "america", "financial", true],
  ["Rio de Janeiro", "Brazil", "America/Sao_Paulo", "america", "financial", false],
  ["Georgetown", "Guyana", "America/Guyana", "america", "capital", false],
  ["Paramaribo", "Suriname", "America/Paramaribo", "america", "capital", false],

  // ===== CHÂU ĐẠI DƯƠNG =====
  ["Canberra", "Úc", "Australia/Sydney", "oceania", "capital", true],
  ["Sydney", "Úc", "Australia/Sydney", "oceania", "financial", true],
  ["Melbourne", "Úc", "Australia/Melbourne", "oceania", "financial", false],
  ["Perth", "Úc", "Australia/Perth", "oceania", "financial", false],
  ["Wellington", "New Zealand", "Pacific/Auckland", "oceania", "capital", true],
  ["Auckland", "New Zealand", "Pacific/Auckland", "oceania", "financial", true],
  ["Suva", "Fiji", "Pacific/Fiji", "oceania", "capital", true],
  ["Port Moresby", "Papua New Guinea", "Pacific/Port_Moresby", "oceania", "capital", false],
  ["Honiara", "Quần đảo Solomon", "Pacific/Guadalcanal", "oceania", "capital", false],
  ["Port Vila", "Vanuatu", "Pacific/Efate", "oceania", "capital", false],
  ["Nouméa", "New Caledonia", "Pacific/Noumea", "oceania", "financial", false],
  ["Apia", "Samoa", "Pacific/Apia", "oceania", "capital", false],
  ["Nuku'alofa", "Tonga", "Pacific/Tongatapu", "oceania", "capital", false],
  ["Palikir", "Micronesia", "Pacific/Pohnpei", "oceania", "capital", false],
  ["Majuro", "Quần đảo Marshall", "Pacific/Majuro", "oceania", "capital", false],
  ["Tarawa", "Kiribati", "Pacific/Tarawa", "oceania", "capital", false],
  ["Funafuti", "Tuvalu", "Pacific/Funafuti", "oceania", "capital", false],
  ["Yaren", "Nauru", "Pacific/Nauru", "oceania", "capital", false],
  ["Ngerulmud", "Palau", "Pacific/Palau", "oceania", "capital", false],
];

const CITIES = CITY_DATA.map(([name, country, tz, continent, type, featured]) => ({
  id: `${name}|${country}`,
  name, country, tz, continent, type, featured,
}));
